
# "Filogenia del género *Piranga* utilizando datos Rad seq"
## Avance3

Resultados:

#nexus
begin data;
  dimensions ntax=30 nchar=2834815;
  format datatype=dna missing=N gap=- interleave=yes;
  matrix
  SRR2503501_1     TAAATCTCAGCAGAAATTTAAGGGAATAATACAGTGGCAAACAAACAGTACAGGCTAGTCAGTAGCAAGGAAATTGTAGCAAAGGAATTGGTCCATGTGT
  SRR2503616_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503707_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTTGGTTCATGTGT
  SRR2503754_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503756_1     TAAATCTCAGCAGAAATTTAAGGGAATAATACAGTGGCAAACAAACAGTACAGGCTAGTCAGTACCAAGGAAATTGTAGCAAAGGAANNNNNNNNNNNNN
  SRR2503757_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503759_1     TAAATCTCAGCAGAAATTTAAGGGAATAATACAGTGGCAAACAAACAGTACAGGCTAGTCAGTACCAAGGAAATTGTAGCAAAGGAATTGGCTCATGTGT
  SRR2503760_1     TAAATCTCAGCAGAAATTTAAGGGAATAATACAGTGGCAAACAAACAGTACAGGCTAGTCAGTACCAAGGAAATTGTAGCAAAGGAATTGGTTCATGTGT
  SRR2503761_1     TAAATCTCAGCAGAAATTNAAGGGANTAATACAGTGGCAAACAAACAGTACAGGCAAGTCAGTACCAAGGAAATTGTAGCAAAGGAANNNNNNNNNNNNN
  SRR2503762_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503763_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503764_1     TAAATCTCAGCAGAAATTTAAGGGAATAATACAGTGGCAAACAAACAGTACAGGCTAGTCAGTACCAAGGAAATTGTAGCAAAGGAANNNNNNNNNNNNN
  SRR2503765_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503766_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503781_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503782_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503783_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503784_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503785_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503786_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503787_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTTGGTTCATGTGT
  SRR2503788_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503790_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTTGGTTCATGTGT
  SRR2503791_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503792_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503794_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503795_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTTGGTTCATGTGT
  SRR2503796_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
  SRR2503797_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTTGGTTCATGTGT
  SRR2503798_1     NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN


### Script:

1. Instalar las funciones toolkit, se bajó toolkit del siguiente link:
https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.9.0/sratoolkit.2.9.0-mac64.tar.gz 
en la ubicación /Users/BEHB/Desktop/trabajo_final.

Descomprimir archivo:
```{bash}
pwd
tar -xzvf  sratoolkit.2.9.0-mac64.tar.gz
```
2. Bajar secuencias en formato sra. En la ubicación: 

```{bash}
cd /Users/BEHB/Desktop/trabajo_final/sratoolkit.2.9.0-mac64/bin
./prefetch --option-file ../../SRR_Acc_List.txt
```
3. Convertir archivos sra en fastq
```{bash}
cd /Users/BEHB/Desktop/trabajo_final/sratoolkit.2.9.0-mac64/bin
./fastq-dump --split-files /Users/BEHB/ncbi/public/sra/*.sra -O ../../data/fastq/
```
4. Instalar ipyrad 
```{bash}

curl -O https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh

bash Miniconda2-latest-MacOSX-x86_64.sh
source ~/.bash_profile
conda info
conda update conda
conda install -c ipyrad ipyrad
ipyrad
```
5. Generar documento de parámetros en ipyrad:
```{bash}
ipyrad -n prueba0_85
```
6. Correr ipyrad
```{bash}
ipyrad -p params-prueba0_85.txt -s 1234567
```

